apiVersion: v1
kind: Service
metadata:
  name: employee-demo-service
  namespace: demo
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: employee-demo
  ports:
    - protocol: TCP
      port: 9190
      targetPort: 9190
