apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-demo
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-demo
  template:
    metadata:
      labels:
        app: employee-demo
    spec:
      containers:
      - name: employee-demo
        image: 360devtester/employee-demo:0.0.1
        imagePullPolicy: IfNotPresent
        env:
        - name: "PORT"
          value: "9190"
        ports:
        - containerPort: 9190
        resources:
          requests:
            cpu: "250m"  # Request 0.25 CPU
          limits:
            cpu: "250m"  # Limit to 0.25 CPU
