apiVersion: v1
kind: Service
metadata:
  name: customer-demo-service
  namespace: demo
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: customer-demo
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
